version: "3.8"

services:
  frontend:
    build: ex1.12
    ports:
      - 127.0.0.1:5000:5000

  backend:
    build: ex1.13
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres:16.2-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
