version: "3.8"

services:
  frontend:
    build:
      context: ex1.12
      args:
        - BACKEND_URL=http://localhost/api

  backend:
    build: ex1.13
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - REQUEST_ORIGIN=http://localhost

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./ex2.8.nginx.conf:/etc/nginx/nginx.conf:ro
