# since Dockerfiles are not involved in docker compose, we'll skip them

version: '3.8'

services:
  frontend:
    image: node:16
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    command: |
      sh -c "
      npm install;
      npm run build;
      npm install -g serve;
      serve -s -l 5000 build
      "
    working_dir: /usr/src/app/
    volumes:
      - ./example-frontend:/usr/src/app/
    depends_on:
      - backend
    container_name: frontend

  backend:
    image: golang:1.16
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    command: |
      sh -c "
        go build;

        # running tests
        go test ./...;
        ./server
      "
    working_dir: /usr/src/app/
    volumes:
      - ./example-backend:/usr/src/app/
    depends_on:
      - redis
      - postgres
    container_name: backend

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres:16.2-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
    - ./ex2.7+gp_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend
